<<<<<<< HEAD
spring.application.name=Employee-Payroll-System
spring.datasource.url=jdbc:mysql://localhost:3306/employee_payroll
=======
spring.application.name=EmployeeManagement 

spring.datasource.url=jdbc:mysql://localhost:3306/employee_db
>>>>>>> 0b13749cfad951019e38c573196ba78a53a5446c
spring.datasource.username=root
spring.datasource.password=Prami@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
<<<<<<< HEAD
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080
>>>>>>> 25639ba58de3961b20fdc9f0c5bad3a60bf8019c
=======
>>>>>>> 0b13749cfad951019e38c573196ba78a53a5446c
