spring.application.name=Employee-Payroll-System
spring.datasource.url=jdbc:mysql://localhost:3306/employee_payroll
spring.datasource.username=root
spring.datasource.password=Prami@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080
>>>>>>> 25639ba58de3961b20fdc9f0c5bad3a60bf8019c
